### ISSUE TITLE
[H without Offset]

### ISSUE THREAD

**Issue by cogito666** [DRNadler/MMC5983MA_CompassTest#1]
Hi there.

Thank for uploading and sharing your knowledge, test result and online hard iron offset.

Another sensor (= mmc5603nj) from MEMSIC is being used for my project.

I got data reading and and there's a thing that I don't understand correctly.

When I observe H which got removed offset (=as you mentioned wrong term by MEMSIC), it's almost the same value even if I rotate the sensor.

Is it correct/expected behavior?

below is my code.
![image](https://github.com/user-attachments/assets/7ced7b80-2395-4c44-9b5a-53049b32dfd7)
<img width="722" alt="image" src="https://github.com/user-attachments/assets/1dc6c387-2d4b-41ed-8c0a-e2c5d5c08819">

**Comment by DRNadler** [comment]
The above looks like incorrect behavior. I have seen this when soldering was done improperly...

These parts have a very limited temperature profile. So, units from SparkFun do not work properly, and initial stuff we built also failed - I think due to too-high heat during soldering. So, first thing to check is the solder profile used during assembly. 

What is the board you are working with?

Hope this helps!
Best Regards, Dave

**Comment by cogito666** [comment]
Hi @DRNadler!

Great to get your response! 

To answer your question, 

1) I used PCBA service on JLCPCB so I need to ask then which temperature profile used for my sensor.
2) nRF52832 with Zephyr RTOS and NRFX driver for DMA.

I was so desperate to solve this issue and I found your posting on the sparkfun dev forum.
It's really weird behavior haha. Maybe as you mentioned, high temperature damaged internal stain gauge inside the chip...

Hmm... As you did, I have official memsic dev board and I will test it.
I will let you know the result!

**Comment by DRNadler** [comment]
Default temperature profile will be too hot.
Ask me how I know ;-(
Looking forward to hearing of your test with Memsic eval board...

**Comment by cogito666** [comment]
> Default temperature profile will be too hot. Ask me how I know ;-( Looking forward to hearing of your test with Memsic eval board...

@DRNadler  Man, I just did it and ... got corret/normal/expected value...
huhu~~~
![image](https://github.com/user-attachments/assets/3ac6ed54-ff02-46f3-a93e-d7b0c87df3ab)

![image](https://github.com/user-attachments/assets/1c5aa02a-5a61-405c-b99e-0e8a8ff56454)

I need to consult with JLCPCB and reorder PCB.

Anyway really appreciate your issue posting. You saved my ass~!!

**Comment by DRNadler** [comment]
Make sure to "Star" this repository on github and close the issue ;-)
Also perhaps fork if you want to receive updates.
Good luck with your project!
Best Regards, Dave

**Comment by cogito666** [comment]
MEMSIC IC is highly sensitive to over temperature during reflow.

Even slight deviation from temperature profile specified in the datasheet, such as an increase of +5 to +10 degree Celsicus, can cause the chip to malfunction or exhibit defects.

This has been confirmed during testing.

**Comment by DRNadler** [comment]
@cogito666 - I updated the documentation in this repository to make the reflow temperature issue clearer.

A few questions if you can spare a moment...
1. Have you got your own board working AOK?
2. What firm did you use for fabrication?
3. Are you using I2C or SPI interface?

Thanks!
Best Regards, Dave
